package com.app.eshop.repositories;
import com.app.eshop.models.CartItem;
import com.app.eshop.models.Product;
import com.app.eshop.models.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CartItemRepository extends JpaRepository<CartItem, Long> {


    CartItem findByUserAndProduct(User user, Product product);

//    Underline query always generated by JPA
//    delete by user and product
    void deleteByUserAndProduct(User user, Product product);

    List<CartItem> findByUser(User user);

    void deleteByUser(User user);
}
